# Generated by Django 5.2.16 on 2026-07-28 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_savings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('ELECTRONICS', 'Electronics'), ('HOUSE', 'House'), ('EDUCATION', 'Education'), ('TRAVEL', 'Travel'), ('OTHER', 'Other')], max_length=20)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_date', models.DateField()),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PURCHASED', 'Purchased'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
