# Generated by Django 5.2.16 on 2026-08-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_purchasegoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_source',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('BANK', 'Bank Account'), ('CASH', 'Cash'), ('CARD', 'Credit Card')], default='BANK', max_length=20),
        ),
    ]
